name: CI tests

on: [push, pull_request]

jobs:
  docs:
    runs-on: ubuntu-22.04
    steps:
      - run: pipx install poetry
      - uses: actions/checkout@v3
      - run: poetry install --only=docs
      - run: poetry run make -C docs/ html
  lint:
    runs-on: ubuntu-22.04
    steps:
      - run: pipx install poetry
      - uses: actions/checkout@v3
      - run: poetry install --only=lint
      - run: poetry run flake8 --show-source
        id: flake8
      - run: poetry run black --check --diff .
        id: black
        if: success() || steps.flake8.conclusion == 'failure'
      - run: poetry run isort --check --diff .
        id: isort
        if: success() || steps.flake8.conclusion == 'failure' || steps.black.conclusion == 'failure'
  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: [ '3.10', '3.11', '3.12' ]
    steps:
      - run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/checkout@v3
      - run: poetry install --only=main --only=test
      - run: poetry run pytest
        if: matrix.python-version != '3.10'
      - run: poetry run coverage run
        if: matrix.python-version == '3.10'
      - run: poetry run coverage xml
        if: matrix.python-version == '3.10'
      - uses: coverallsapp/github-action@v2
        if: matrix.python-version == '3.10'
        with:
          file: coverage.xml
